//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALFeedUpdates
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FeedUpdatesEntities : DbContext
    {
        public FeedUpdatesEntities()
            : base("name=FeedUpdatesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int ProcessQueueInfoToSyX(string rMQJson, Nullable<int> sportsID)
        {
            var rMQJsonParameter = rMQJson != null ?
                new ObjectParameter("RMQJson", rMQJson) :
                new ObjectParameter("RMQJson", typeof(string));
    
            var sportsIDParameter = sportsID.HasValue ?
                new ObjectParameter("SportsID", sportsID) :
                new ObjectParameter("SportsID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessQueueInfoToSyX", rMQJsonParameter, sportsIDParameter);
        }
    }
}
